// UTF-8
const beaches = [
  { id: "hamdeok", name: "함덕해수욕장", region: "제주시", address: "제주시 조천읍 함덕리", beachHint: "함덕해수욕장" },
  { id: "gimnyeong", name: "김녕해수욕장", region: "제주시", address: "제주시 구좌읍 김녕리", beachHint: "김녕해수욕장" },
  { id: "woljeong", name: "월정리해변", region: "제주시", address: "제주시 구좌읍 월정리", beachHint: "월정리해수욕장" },
  { id: "sehwa", name: "세화해변", region: "제주시", address: "제주시 구좌읍 세화리", beachHint: "세화해수욕장" },
  { id: "hado", name: "하도해변", region: "제주시", address: "제주시 구좌읍 하도리", beachHint: "하도해수욕장" },
  { id: "jongdal", name: "종달리해변", region: "제주시", address: "제주시 구좌읍 종달리", beachHint: "종달리해수욕장" },
  { id: "gwakji", name: "곽지해수욕장", region: "제주시", address: "제주시 애월읍 곽지리", beachHint: "곽지해수욕장" },
  { id: "handam", name: "애월 한담해변", region: "제주시", address: "제주시 애월읍 애월리", beachHint: "한담해수욕장" },
  { id: "hagwi_rock_spot", name: "하귀해변 암반 스팟", region: "제주시", address: "제주특별자치도 제주시 애월읍 고내리 445-3", beachHint: "곽지해수욕장" },
  { id: "hyeopjae", name: "협재해수욕장", region: "제주시", address: "제주시 한림읍 협재리", beachHint: "협재해수욕장" },
  { id: "geumneung", name: "금능해수욕장", region: "제주시", address: "제주시 한림읍 금능리", beachHint: "금능해수욕장" },
  { id: "geumneung-sumun", name: "금능 수문 포인트", region: "제주시", address: "제주시 한림읍 금능리 수문", beachHint: "금능해수욕장" },
  { id: "biyangdo", name: "비양도 해안", region: "제주시", address: "제주시 한림읍 비양도", beachHint: "협재해수욕장" },
  { id: "hallim-harbor", name: "한림항 방파제 포인트", region: "제주시", address: "제주시 한림읍 한림리", beachHint: "협재해수욕장" },
  { id: "ihoteu", name: "이호테우해변", region: "제주시", address: "제주시 도두동", beachHint: "이호테우해수욕장" },
  { id: "dodu", name: "도두해안", region: "제주시", address: "제주시 도두동", beachHint: "이호테우해수욕장" },
  { id: "samyang", name: "삼양해수욕장", region: "제주시", address: "제주시 삼양동", beachHint: "삼양해수욕장" },
  { id: "naedo_snorkel", name: "내도 스노클링 포인트", region: "제주시", address: "제주특별자치도 제주시 테우해안로 60", beachHint: "곽지해수욕장" },
  { id: "oedo", name: "외도 바닷물풀장", region: "제주시", address: "제주시 외도동", beachHint: "이호테우해수욕장" },
  { id: "jungmun", name: "중문 색달해변", region: "서귀포시", address: "서귀포시 색달동", beachHint: "중문해수욕장" },
  { id: "daepo", name: "대포 주상절리 앞 스노클 포인트", region: "서귀포시", address: "서귀포시 대포동", beachHint: "중문해수욕장" },
  { id: "beophwan", name: "법환포구(얕은 스노클 구역)", region: "서귀포시", address: "서귀포시 법환동", beachHint: "중문해수욕장" },
  { id: "hwasun", name: "화순금모래해변", region: "서귀포시", address: "서귀포시 안덕면 화순리", beachHint: "화순해수욕장" },
  { id: "sagye", name: "사계 포구(프리다이빙 명소)", region: "서귀포시", address: "서귀포시 안덕면 사계리", beachHint: "사계해변" },
  { id: "songaksan_spot", name: "송악산 해안 포인트", region: "서귀포시", address: "제주특별자치도 서귀포시 대정읍 최남단해안로 548-88", beachHint: "사계해변" },
  { id: "hamo", name: "하모해변(모슬포)", region: "서귀포시", address: "서귀포시 대정읍 하모리", beachHint: "하모해수욕장" },
  { id: "sinyeong", name: "신양 섭지해수욕장", region: "서귀포시", address: "서귀포시 성산읍 신양리", beachHint: "신양섭지해수욕장" },
  { id: "seopjikoji_snorkel", name: "섭지코지 스노클 포인트", region: "서귀포시", address: "제주특별자치도 서귀포시 성산읍 섭지코지로 107", beachHint: "신양섭지해수욕장" },
  { id: "gwangchigi_beach", name: "광치기해변", region: "서귀포시", address: "제주특별자치도 서귀포시 성산읍 섭지코지로 63", beachHint: "광치기해변" },
  { id: "pyoseon", name: "표선해수욕장", region: "서귀포시", address: "서귀포시 표선면 표선리", beachHint: "표선해수욕장" },
  { id: "pyoseon_south_snorkel", name: "표선 남쪽 스노클 포인트", region: "서귀포시", address: "제주특별자치도 서귀포시 표선면 민속해안로 615", beachHint: "표선해수욕장" },
  { id: "onpyeong", name: "온평리 해안 스팟", region: "서귀포시", address: "서귀포시 성산읍 온평리", beachHint: "표선해수욕장" },
  { id: "namwon", name: "남원 큰엉 해안", region: "서귀포시", address: "서귀포시 남원읍 남원리", beachHint: "남원해수욕장" },
  { id: "bomok", name: "보목해변", region: "서귀포시", address: "서귀포시 보목동", beachHint: "보목해수욕장" },
  { id: "hoesudong_coast", name: "회수동 해안 포인트", region: "서귀포시", address: "제주특별자치도 서귀포시 회수동 53-1", beachHint: "중문해수욕장" },
  { id: "nonjitmul_beach", name: "논짓물 해변", region: "서귀포시", address: "제주특별자치도 서귀포시 논짓물로 38", beachHint: "남원해수욕장" },
  { id: "pyoseon_south", name: "표선 남쪽 스노쿨 포인트", region: "서귀포시", address: "제주특별자치도 서귀포시 표선면 표선리 표선해수욕장 남쪽 해안", beachHint: "표선해수욕장" },
  { id: "sinyang_beach", name: "신양섭지해수욕장", region: "서귀포시", address: "제주특별자치도 서귀포시 성산읍 섭지코지로 107", beachHint: "신양섭지해수욕장" },
  { id: "geumnung_gate", name: "금능 수문 포인트", region: "제주시", address: "제주특별자치도 제주시 한림읍 금능길 119-10", beachHint: "금능해수욕장" }
];
